const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();
async function main() {
  const users = await prisma.User.createMany({
    data: [
      {
        phone: "+251912345678",
        password: "password1",
        role: "USER",
        fullname: "John Doe",
        aboutagent: "General user with no agent role.",
      },
      {
        phone: "+251912345679",
        password: "password2",
        role: "USER",
        fullname: "Jane Smith",
        aboutagent: "Regular user account.",
      },
      {
        phone: "+251912345680",
        password: "password3",
        role: "AGENT",
        fullname: "Mike Johnson",
        aboutagent:
          "Top agent specializing in high-value clients Top agent specializing in high-value clients Top agent specializing in high-value clients Top agent specializing in high-value clients.",
      },
      {
        phone: "+251912345681",
        password: "password4",
        role: "ADMIN",
        fullname: "Admin User",
        aboutagent: "Administrator with full permissions.",
      },
      {
        phone: "+251912345682",
        password: "password5",
        role: "USER",
        fullname: "Sarah Connor",
        aboutagent: "Enthusiastic user with a passion for feedback.",
      },
      {
        phone: "+251912345683",
        password: "password6",
        role: "AGENT",
        fullname: "James Bond",
        aboutagent:
          "Top agent specializing in high-value clients Top agent specializing in high-value clients Top agent specializing in high-value clients Top agent specializing in high-value clients.",
      },
      {
        phone: "+251912345684",
        password: "password6",
        role: "AGENT",
        fullname: "James Bond",
        aboutagent:
          "Top agent specializing in high-value clients Top agent specializing in high-value clients Top agent specializing in high-value clients Top agent specializing in high-value clients.",
      },
      {
        phone: "+251912345685",
        password: "password6",
        role: "AGENT",
        fullname: "James Bond",
        aboutagent:
          "Top agent specializing in high-value clients Top agent specializing in high-value clients Top agent specializing in high-value clients Top agent specializing in high-value clients.",
      },
    ],
  });

  console.log(`Created ${users.count} users.`);

  const products = await prisma.product.createMany({
    data: [
      {
        agentId: 4, // Assuming the third user is an agent
        type: "HOUSE",
        title: "150m House",
        description: "A beautiful luxury house.",
        numberOfBeds: 3,
        numberOfSeats: 5,
        color: "blue",
        price: 300000,
        K_Ketema: "Central",
        Woreda: "1",
        HouseNumber: "101",
        images: JSON.stringify(["image1.jpg", "image2.jpg"]),
        available: true,
      },
      {
        agentId: 2,
        type: "CAR",
        title: "Vitz Car",
        description: "A fast sport car.",
        numberOfBeds: 0,
        numberOfSeats: 2,
        color: "red",
        price: 50000,
        K_Ketema: "North",
        Woreda: "2",
        HouseNumber: null,
        images: JSON.stringify(["image3.jpg"]),
        available: true,
      },
      {
        agentId: 4, // Assuming the fourth user is an agent
        type: "APARTMENT",
        title: "Noh Apartment",
        description: "A cozy apartment in the city.",
        numberOfBeds: 1,
        numberOfSeats: 4,
        color: "green",
        price: 150000,
        K_Ketema: "East",
        Woreda: "3",
        HouseNumber: "202",
        images: JSON.stringify(["image4.jpg"]),
        available: true,
      },
      {
        agentId: 5,
        type: "CONDOMINIUM",
        title: "Koye Condominium",
        description: "A stylish condominium with modern amenities.",
        numberOfBeds: 1,
        numberOfSeats: 6,
        color: "black",
        price: 25000,
        K_Ketema: "South",
        Woreda: "4",
        HouseNumber: "303",
        images: JSON.stringify(["image5.jpg"]),
        available: true,
      },
      {
        agentId: 6,
        type: "HOUSE",
        title: "STUDIO House",
        description: "A spacious family house.",
        numberOfBeds: 2,
        numberOfSeats: 8,
        color: "yellow",
        price: 40000,
        K_Ketema: "West",
        Woreda: "5",
        HouseNumber: "404",
        images: JSON.stringify(["image6.jpg"]),
        available: true,
      },
      {
        agentId: 4, // Assuming the third user is an agent
        type: "HOUSE",
        title: "700m House",
        description: "A beautiful luxury house.",
        numberOfBeds: 3,
        numberOfSeats: 5,
        color: "blue",
        price: 300000,
        K_Ketema: "Central",
        Woreda: "1",
        HouseNumber: "101",
        images: JSON.stringify(["image1.jpg", "image2.jpg"]),
        available: true,
      },
      {
        agentId: 2,
        type: "CAR",
        title: "BYD Car",
        description: "A fast sport car.",
        numberOfBeds: 0,
        numberOfSeats: 4,
        color: "red",
        price: 50000,
        K_Ketema: "North",
        Woreda: "2",
        HouseNumber: null,
        images: JSON.stringify(["image3.jpg"]),
        available: true,
      },
      {
        agentId: 4, // Assuming the fourth user is an agent
        type: "APARTMENT",
        title: "Belay Apartment",
        description: "A cozy apartment in the city.",
        numberOfBeds: 3,
        numberOfSeats: 4,
        color: "green",
        price: 150000,
        K_Ketema: "East",
        Woreda: "3",
        HouseNumber: "202",
        images: JSON.stringify(["image4.jpg"]),
        available: true,
      },
      {
        agentId: 5,
        type: "CONDOMINIUM",
        title: "Ayat Condominium",
        description: "A stylish condominium with modern amenities.",
        numberOfBeds: 2,
        numberOfSeats: 6,
        color: "black",
        price: 25000,
        K_Ketema: "South",
        Woreda: "4",
        HouseNumber: "303",
        images: JSON.stringify(["image5.jpg"]),
        available: true,
      },
      {
        agentId: 6,
        type: "HOUSE",
        title: "STUDIO House",
        description: "A spacious family house.",
        numberOfBeds: 1,
        numberOfSeats: 8,
        color: "yellow",
        price: 40000,
        K_Ketema: "West",
        Woreda: "5",
        HouseNumber: "404",
        images: JSON.stringify(["image6.jpg"]),
        available: true,
      },
      {
        agentId: 5,
        type: "CONDOMINIUM",
        title: "Lideta Condominium",
        description: "A stylish condominium with modern amenities.",
        numberOfBeds: 1,
        numberOfSeats: 6,
        color: "black",
        price: 25000,
        K_Ketema: "South",
        Woreda: "4",
        HouseNumber: "303",
        images: JSON.stringify(["image5.jpg"]),
        available: true,
      },
      {
        agentId: 5,
        type: "CONDOMINIUM",
        title: "Ayat Condominium",
        description: "A stylish condominium with modern amenities.",
        numberOfBeds: 2,
        numberOfSeats: 6,
        color: "black",
        price: 25000,
        K_Ketema: "South",
        Woreda: "4",
        HouseNumber: "303",
        images: JSON.stringify(["image5.jpg"]),
        available: true,
      },
      {
        agentId: 5,
        type: "CONDOMINIUM",
        title: "Lideta Condominium",
        description: "A stylish condominium with modern amenities.",
        numberOfBeds: 3,
        numberOfSeats: 6,
        color: "black",
        price: 25000,
        K_Ketema: "South",
        Woreda: "4",
        HouseNumber: "303",
        images: JSON.stringify(["image5.jpg"]),
        available: true,
      },
      {
        agentId: 5,
        type: "CONDOMINIUM",
        title: "Noh Condominium",
        description: "A stylish condominium with modern amenities.",
        numberOfBeds: 2,
        numberOfSeats: 6,
        color: "black",
        price: 25000,
        K_Ketema: "South",
        Woreda: "4",
        HouseNumber: "303",
        images: JSON.stringify(["image5.jpg"]),
        available: true,
      },
      {
        agentId: 5,
        type: "CONDOMINIUM",
        title: "Ayat Condominium",
        description: "A stylish condominium with modern amenities.",
        numberOfBeds: 2,
        numberOfSeats: 6,
        color: "black",
        price: 25000,
        K_Ketema: "South",
        Woreda: "4",
        HouseNumber: "303",
        images: JSON.stringify(["image5.jpg"]),
        available: true,
      },
      {
        agentId: 4, // Assuming the fourth user is an agent
        type: "APARTMENT",
        title: "OVID Apartment",
        description: "A cozy apartment in the city.",
        numberOfBeds: 3,
        numberOfSeats: 4,
        color: "green",
        price: 150000,
        K_Ketema: "East",
        Woreda: "3",
        HouseNumber: "202",
        images: JSON.stringify(["image4.jpg"]),
        available: true,
      },
      {
        agentId: 4, // Assuming the fourth user is an agent
        type: "APARTMENT",
        title: "Belay Apartment",
        description: "A cozy apartment in the city.",
        numberOfBeds: 3,
        numberOfSeats: 4,
        color: "green",
        price: 150000,
        K_Ketema: "East",
        Woreda: "3",
        HouseNumber: "202",
        images: JSON.stringify(["image4.jpg"]),
        available: true,
      },
      {
        agentId: 4, // Assuming the fourth user is an agent
        type: "APARTMENT",
        title: "OVID Apartment",
        description: "A cozy apartment in the city.",
        numberOfBeds: 3,
        numberOfSeats: 4,
        color: "green",
        price: 150000,
        K_Ketema: "East",
        Woreda: "3",
        HouseNumber: "202",
        images: JSON.stringify(["image4.jpg"]),
        available: true,
      },
      {
        agentId: 4, // Assuming the fourth user is an agent
        type: "APARTMENT",
        title: "Noh Apartment",
        description: "A cozy apartment in the city.",
        numberOfBeds: 3,
        numberOfSeats: 4,
        color: "green",
        price: 150000,
        K_Ketema: "East",
        Woreda: "3",
        HouseNumber: "202",
        images: JSON.stringify(["image4.jpg"]),
        available: true,
      },
    ],
  });

  console.log(`Created ${products.count} products.`);
  console.log("Sample data seeded successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
