import React, { ReactNode } from "react";
import Head from "next/head";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar"; // Ensure Navbar path is correct
import { DataProvider } from "@/app/providerscripts/DataContext";
import { CheckboxProvider } from "@/app/providerscripts/contectboxprovider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Delala",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <title>My Fullstack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DataProvider>
        <CheckboxProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Navbar>{children}</Navbar>
          </body>
        </CheckboxProvider>
      </DataProvider>
    </html>
  );
}
