import Head from 'next/head';
import UserList from '../components/UserList';
import Navbar from '@/components/Navbar';
import { CheckboxProvider } from '../components/providerscripts/contectboxprovider'; 
import '../app/globals.css';

export default function Home() {
  return (
    <div>
          <CheckboxProvider>
      <Head>
        <title>My Fullstack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Navbar/>
      
      </main>
      </CheckboxProvider>
    </div>
  );
}